import { useEffect, useMemo, useRef, useState } from 'react';
import { fetchSpatialPoints, runSpatialQuery } from '../api';
import type { SpatialKind, SpatialMetric, SpatialPoint, SpatialQueryResult, TableInfo } from '../types';

declare global { interface Window { L?: any; } }
interface Props { tables: TableInfo[]; selectedTable: string | null; onSelectTable: (name:string)=>void; }
interface LatLon { lat:number; lon:number; }

export default function MapPanel({ tables, selectedTable, onSelectTable }: Props) {
  const mapEl=useRef<HTMLDivElement|null>(null); const mapRef=useRef<any>(null); const layerRef=useRef<any>(null); const resultLayerRef=useRef<any>(null);
  const [allPoints,setAllPoints]=useState<SpatialPoint[]>([]); const [error,setError]=useState<string|null>(null); const [center,setCenter]=useState<LatLon>({lat:-12.0464,lon:-77.0428}); const [kind,setKind]=useState<SpatialKind>('range'); const [metric,setMetric]=useState<SpatialMetric>('haversine'); const [radius,setRadius]=useState(5000); const [k,setK]=useState(10); const [polygonText,setPolygonText]=useState(''); const [result,setResult]=useState<SpatialQueryResult|null>(null); const [busy,setBusy]=useState(false);
  const spatialTables=useMemo(()=>tables.filter(t=>t.indexes.some(i=>i.kind==='rtree')||t.schema.columnas.some(([c])=>['lat','latitud','latitude'].includes(c.toLowerCase()))),[tables]);
  const polygon=useMemo(()=>polygonText.split(/[;\n]+/).map(s=>s.trim()).filter(Boolean).map(s=>s.split(/[ ,]+/).map(Number) as [number,number]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1])),[polygonText]);
  useEffect(()=>{ const L=window.L;if(!L||!mapEl.current||mapRef.current)return; const map=L.map(mapEl.current).setView([center.lat,center.lon],12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map); layerRef.current=L.layerGroup().addTo(map);resultLayerRef.current=L.layerGroup().addTo(map);map.on('click',(e:any)=>setCenter({lat:e.latlng.lat,lon:e.latlng.lng}));mapRef.current=map;return()=>{map.remove();mapRef.current=null;};},[]);
  useEffect(()=>{ if(!selectedTable){setAllPoints([]);return;} setError(null);fetchSpatialPoints(selectedTable).then(data=>{setAllPoints(data.points);if(data.bounds){setCenter({lat:(data.bounds.min_lat+data.bounds.max_lat)/2,lon:(data.bounds.min_lon+data.bounds.max_lon)/2});const L=window.L;if(mapRef.current&&L)mapRef.current.fitBounds([[data.bounds.min_lat,data.bounds.min_lon],[data.bounds.max_lat,data.bounds.max_lon]],{padding:[20,20]});}}).catch(e=>{setAllPoints([]);setError(e instanceof Error?e.message:String(e));});},[selectedTable]);
  useEffect(()=>{const L=window.L;if(!L||!layerRef.current)return;layerRef.current.clearLayers();for(const p of allPoints){L.circleMarker([p.lat,p.lon],{radius:4,weight:1,fillOpacity:.65}).bindTooltip(p.label??p.rid).addTo(layerRef.current);}},[allPoints]);
  useEffect(()=>{const L=window.L;if(!L||!resultLayerRef.current)return;resultLayerRef.current.clearLayers();if(!result)return;for(const p of result.points){L.circleMarker([p.lat,p.lon],{radius:7,weight:3,fillOpacity:.9}).bindPopup(`${p.label??p.rid}${p.distance_m!==null?`<br>${p.distance_m.toFixed(2)} ${result.distance_unit}`:''}`).addTo(resultLayerRef.current);}L.marker([center.lat,center.lon]).bindTooltip('Punto de consulta').addTo(resultLayerRef.current);if(kind==='range')L.circle([center.lat,center.lon],{radius}).addTo(resultLayerRef.current);if(kind==='polygon'&&polygon.length>=3)L.polygon(polygon.map(([lat,lon])=>[lat,lon])).addTo(resultLayerRef.current);},[result,center,kind,radius,polygon]);
  async function search(){if(!selectedTable)return;setBusy(true);setError(null);try{const r=await runSpatialQuery({table:selectedTable,kind,lat:center.lat,lon:center.lon,radius_m:radius,k,metric,polygon:kind==='polygon'?polygon:undefined});if(!r.success)throw new Error(r.error??'Consulta espacial falló');setResult(r);}catch(e){setResult(null);setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <div className="panel"><h2 className="panel__title">Panel de mapa</h2><p className="panel__hint">Leaflet + OpenStreetMap. Haz clic para fijar el punto de consulta y ejecuta rango, k-NN o polígono.</p><div className="map__controls">
    <label className="field"><span>Tabla espacial</span><select className="select" value={selectedTable??''} onChange={e=>onSelectTable(e.target.value)}><option value="">— seleccionar —</option>{spatialTables.map(t=><option key={t.name} value={t.name}>{t.name}</option>)}</select></label>
    <label className="field"><span>Modo</span><select className="select" value={kind} onChange={e=>setKind(e.target.value as SpatialKind)}><option value="range">Rango</option><option value="knn">k-NN</option><option value="polygon">Polígono</option></select></label>
    <label className="field"><span>Métrica</span><select className="select" value={metric} onChange={e=>setMetric(e.target.value as SpatialMetric)}><option value="haversine">Haversine</option><option value="euclidean">Euclidiana</option></select></label>
    <label className="field"><span>Radio (m)</span><input className="input" type="number" value={radius} disabled={kind!=='range'} onChange={e=>setRadius(Number(e.target.value))}/></label>
    <label className="field"><span>k</span><input className="input" type="number" value={k} disabled={kind!=='knn'} onChange={e=>setK(Number(e.target.value))}/></label>
    {kind==='polygon'&&<label className="field field--wide"><span>Vértices lat,lon; …</span><input className="input" value={polygonText} onChange={e=>setPolygonText(e.target.value)} placeholder="-12.05,-77.05; -12.05,-77.00; -12.10,-77.02"/></label>}
    <button type="button" className="button button--primary" disabled={!selectedTable||busy} onClick={()=>void search()}>{busy?'Buscando…':'Buscar'}</button></div>
    <div ref={mapEl} className="leaflet-map" />
    <p className="panel__hint">Consulta: {center.lat.toFixed(5)}, {center.lon.toFixed(5)} · Puntos cargados: {allPoints.length}</p>{error&&<div className="alert alert--error">{error}</div>}{result&&<div className="metrics"><span>{result.access_path}</span><span>{result.points.length} resultados</span><span>{result.execution_time_ms.toFixed(3)} ms</span></div>}
  </div>;
}
